name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from plugin file
        id: get_version
        run: |
          VERSION=$(grep -m 1 "Version:" time-progress.php | awk -F': ' '{print $2}' | tr -d '\r')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create plugin archive
        run: |
          mkdir time-progress
          cp -r css js languages time-progress.php README.md LICENSE time-progress/
          zip -r time-progress.zip time-progress

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: time-progress.zip
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} 